---

- name: Logout API
  hosts: localhost

  vars:
    access: "{{ lookup('file','/tmp/token_{{ ip }}.yaml') }}"
  tasks:

    - name: Performing Logout
      uri:
        url: "https://{{ ip }}:8888/restapi/v2/logout"
        headers:
          Authorization: "Bearer {{ access }}"
          Content-Type: 'application/json'
        validate_certs: no
        follow_redirects: all
        return_content: yes
        status_code: 200
        method: PUT
      register: result

    - name: STATUS
      ansible.builtin.debug:
        var: result.content

    - name: Invalidating Token
      file:
        path: /tmp/token_{{ ip }}.yaml
        state: absent

    - name: Invalidating Refresh Token
      file:
        path: /tmp/refreshToken_{{ ip }}.yaml
        state: absent

