---
- name: VM Create API
  hosts: localhost
  vars:
    access: "{{ lookup('file','/tmp/token_{{ ip }}.yaml') }}"
  tasks:
    - name: Creating VM
      ansible.builtin.uri:
        url: "https://{{ ip }}/restapi/v2/virtualmachines/vmcreate"
        headers:
          Authorization: "Bearer {{ access }}"
          Content-Type: 'application/json'
        method: POST
        body_format: json
        body: '{
          "vmname": "{{vmname}}",
          "description": "{{description}}",
          "bootType": "{{bootType}}",
          "virtualCpus": "{{virtualCpus}}",
          "memory": "{{memory}}",
          "availabilityLevel": "{{availabilityLevel}}",
          "prefferednode": "{{prefferednode}}",
          "volumes": ["{{volumes}}"],
          "remotetype": "{{remotetype}}",
          "remoteisopath": "{{remoteisopath}}",
          "network": ["{{network}}"]
        }'
        validate_certs: no
        status_code: 200
        timeout: 100
      register: result
    - name: Status
      ansible.builtin.debug:
        var: result

