---
- name: Work ON API
  hosts: localhost
  vars:
    access: "{{ lookup('file','/tmp/token_{{ ip }}.yaml') }}"
  tasks:
    - name: Putting {{node}} to Maintenance
      ansible.builtin.uri:
        url: "https://{{ ip }}/restapi/v2/physicalmachines/workon"
        headers:
          Authorization: "Bearer {{ access }}"
          Content-Type: 'application/json'
        method: POST
        body_format: json
        body: '{
          "nodeName": "{{node}}",
          "force": "{{true}}"
        }'
        validate_certs: no
        follow_redirects: all
        return_content: yes
        status_code: 200
        timeout: 30
      register: result
    - name: STATUS
      ansible.builtin.debug:
        var: result.content




