---
- name: Login Aunthentication
  hosts: localhost
  tasks:
    - name: Generating Token
      ansible.builtin.uri:
        url: "https://{{ip}}:8888/restapi/v2/login"
        method: POST
        body_format: json
        body: '{
          "username": "{{usrname}}",
          "password": "{{pswrd}}"
        }'
        validate_certs: no
        status_code: 200
        timeout: 30
      register: result
    - name: token generated
      ansible.builtin.debug:
        msg: "TOKEN GENERATED SUCCESSFULLY"

    - name: Saving the Token
      ansible.builtin.copy:
        content: "{{ result.json.token }}"
        dest: /tmp/token_{{ ip }}.yaml
    - name: Saving the Refresh Token
      ansible.builtin.copy:
        content: "{{ result.json.refreshToken }}"
        dest: /tmp/refreshToken_{{ ip }}.yaml
