---

- name: Deleting Existing file
  ansible.builtin.file:
    path: "{{ cluster }}"
    state: absent
- name: Creating a file for "{{ ip }}"
  file:
    path: "{{ cluster }}"
    state: touch
- name: Login "{{ ip }}"
  ansible.builtin.uri:
    url: "https://{{ ip }}:8888/restapi/v2/login"
    method: POST
    body_format: json
    body: '{
      "username": "{{usrname}}",
      "password": "{{pswrd}}"
    }'
    validate_certs: no
    status_code: 200
    timeout: 30
  register: result
- name: token generated
  ansible.builtin.debug:
    var: result.json
- name: Storing Token
  ansible.builtin.copy:
    content: "{{ result.json.token }}"
    dest: "{{ token }}"
- name: Storing Refresh Token
  ansible.builtin.copy:
    content: "{{ result.json.refreshToken }}"
    dest: "{{ refresh }}"
- name: Storing LOGIN API result in the file
  lineinfile:
    path: "{{ cluster }}"
    line: "{{result.json}}\n"

- name: Fetching Summary "{{ ip }}"
  uri:
    url: "https://{{ ip }}/restapi/v2/summary"
    headers:
      Authorization: "Bearer {{ access }}" 
      Content-Type: 'application/json'
    validate_certs: no
    follow_redirects: all
    return_content: yes
    status_code: 200
    method: GET
  register: Summary

- name: STATUS
  ansible.builtin.debug:
    var: Summary.content

- name: Storing Summary API result in the file
  lineinfile:
    path: "{{ cluster }}"
    line: "{{Summary.content}}\n"

- name: Fetching VM Information "{{ ip }}"
  uri:
    url: "https://{{ ip }}/restapi/v2/resource/virtualmachines"
    headers:
      Authorization: "Bearer {{ access }}" 
      Content-Type: 'application/json'
    validate_certs: no
    follow_redirects: all
    return_content: yes
    status_code: 200
    method: GET
  register: VM_Info

- name: STATUS
  ansible.builtin.debug:
    var: VM_Info.content

- name: Storing VM INFO API result in the file
  lineinfile:
    path: "{{ cluster }}"
    line: "{{VM_Info.content}}\n"

- name: Performing Logout "{{ ip }}"
  uri:
    url: "https://{{ ip }}:8888/restapi/v2/logout"
    headers:
      Authorization: "Bearer {{ access }}"
      Content-Type: 'application/json'
    validate_certs: no
    follow_redirects: all
    return_content: yes
    status_code: 200
    method: PUT
  register: LogoutInfo

- name: STATUS
  ansible.builtin.debug:
    var: LogoutInfo.content
- name: Storing LOGOUT API result in the file
  lineinfile:
    path: "{{ cluster }}"
    line: "{{LogoutInfo.content}}\n"

- name: Storing Summary API result in the file
  lineinfile:
    path: "ClusterInfo.txt"
    line: "{{ result }}\n {{Summary.content}}\n {{VM_Info.content}}\n {{LogoutInfo.content}}\n\n"
