---
- name: DISPLAYING ALL CLUSTER INFORMATION
  hosts: localhost
  vars_files:
    - config.yaml
  vars_prompt:
    - name: address
      prompt: Enter the IPs (comma-seperated)
      private: false
    - name: usrname
      prompt: Enter Username
      private: false
    - name: pswrd
      prompt: Enter Password
      private: true
  tasks:
  - name: Deleting Existing master file
    ansible.builtin.file:
      path: "ClusterInfo.txt"
      state: absent
  - name: Creating a MASTER FILE
    file:
      path: "ClusterInfo.txt"
      state: touch

  - name: Fetching Details
    set_fact:
      ip_list: "{{address.split(',')}}"
  - include_tasks: clusterinfotask.yaml
    vars:
      ip: "{{ lookup('vars', item) }}"
      token: "token_{{ ip }}.yaml"
      refresh: "refreshToken_{{ ip }}.yaml"
      cluster: "ClusterInfo_{{ ip }}.txt"
      access: "{{ lookup('file','token_{{ ip }}.yaml') }}"
      wtok: "null"
    loop: "{{ ip_list }}"




