---
- name: login
  ansible.builtin.uri:
    url: "https://{{ ip }}:8888/restapi/v2/login"
    method: POST
    body_format: json
    body: '{
      "username": "{{usrname}}",
      "password": "{{pswrd}}"
    }'
    validate_certs: no
    status_code: 200
    timeout: 30
  register: result
- name: token generated
  ansible.builtin.debug:
    var: result.json
- name: Storing Token
  ansible.builtin.copy:
    content: "{{ result.json.token }}"
    dest: "{{ token }}"
- name: Storing Refresh Token
  ansible.builtin.copy:
    content: "{{ result.json.refreshToken }}"
    dest: "{{ refresh }}"

