---

- name: Logout API
  hosts: localhost
  vars_prompt:
    - name: ip
      prompt: Enter System IP
      private: false

  vars:
    access: "{{ lookup('file','token_{{ ip }}.yaml') }}"
    wtok: "null"
    token: "token_{{ ip }}.yaml"
  tasks:

    - name: Performing Logout
      uri:
        url: "https://{{ ip }}:8888/restapi/v2/logout"
        headers:
          Authorization: "Bearer {{ access }}"
          Content-Type: 'application/json'
        validate_certs: no
        follow_redirects: all
        return_content: yes
        status_code: 200
        method: PUT
      register: result

    - name: STATUS
      ansible.builtin.debug:
        var: result.content

    - name: Storing Token
      ansible.builtin.copy:
        content: "{{ wtok }}"
        dest: "{{ token }}"
