---
- name: Loop
  hosts: localhost
  vars_prompt:
    - name: ip
      prompt: Enter the IPs (comma-seperated)
      private: false
  tasks:
  - name: IP Looo
    set_fact:
      ip_list: "{{ ip.split(',') }}"
      name: Login Aunthentication
      vars_prompt:
       # - name: ip
          #prompt: Enter System IP
          #private: false
        - name: usrname
          prompt: Enter Username
          private: false
        - name: pswrd
          prompt: Enter Password
          private: true
      vars:
        server: "https://{{ ip }}:8888/restapi"
        endpoint: "/v2/login"
        token: "token_{{ ip }}.yaml"
        refresh: "refreshToken_{{ ip }}.yaml"
      tasks:
        - name: login
          ansible.builtin.uri:
            url: "{{ server }}{{ endpoint }}"
            method: POST
            body_format: json
            body: '{
              "username": "{{usrname}}",
              "password": "{{pswrd}}"
            }'
            validate_certs: no
            status_code: 200
            timeout: 30
          register: result
        - name: token generated
          ansible.builtin.debug:
            var: result.json
        - name: Storing Token
          ansible.builtin.copy:
            content: "{{ result.json.token }}"
            dest: "{{ token }}"
        - name: Storing Refresh Token
          ansible.builtin.copy:
            content: "{{ result.json.refreshToken }}"
            dest: "{{ refresh }}"
    
    loop: "{{ ip_list }}"
