---
- name: Node Shutdown API
  hosts: localhost
  vars_prompt:
    - name: ip
      prompt: Enter System IP
      private: false
    - name: node
      prompt: Enter Node Name
      private: false
    - name: finalize
      prompt: Do you want Auto Finalize on POWER ON (true/false)
      private: false
  vars:
    access: "{{ lookup('file','token_{{ ip }}.yaml') }}"
  tasks:
    - name: Shutting Down {{node}}
      ansible.builtin.uri:
        url: "https://{{ ip }}:8888/restapi/v2/physicalmachines/nodeshutdown"
        headers:
          Authorization: "Bearer {{ access }}"
          Content-Type: 'application/json'
        method: POST
        body_format: json
        body: '{
          "nodeName": "{{node}}",
          "autoFinalize": "{{finalize}}"
        }'
        validate_certs: no
        follow_redirects: all
        return_content: yes
        status_code: 200
        timeout: 30
      register: result
    - name: STATUS
      ansible.builtin.debug:
        var: result.content
