---

- name: Refresh Token  API
  hosts: localhost
  vars_prompt:
    - name: ip
      prompt: Enter System IP
      private: false
  vars:
    access: "{{ lookup('file','refreshToken_{{ ip }}.yaml') }}"
    token: "token_{{ ip }}.yaml"
  tasks:

    - name: Fetching Refresh Token
      uri:
        url: "https://{{ ip }}:8888/restapi/v2/refreshtoken"
        body_format: json
        body: '{
          "refreshToken": "{{access}}",
        }'

        validate_certs: no
        follow_redirects: all
        return_content: yes
        status_code: 200
        method: POST
      register: result
    - name: token generated
      ansible.builtin.debug:
        var: result.json
    - name: Storing Token
      ansible.builtin.copy:
        content: "{{ result.json.token }}"
        dest: "{{ token }}"
