---

    - name: Fetching Summary
      uri:
        url: "https://{{ ip }}/restapi/v2/summary"
        headers:
          Authorization: "Bearer {{ access }}" 
          Content-Type: 'application/json'
        validate_certs: no
        follow_redirects: all
        return_content: yes
        status_code: 200
        method: GET
      register: Summary

    - name: STATUS
      ansible.builtin.debug:
        var: Summary.content
