    - name: Putting {ip} to shutdown
      uri:
        url: "https://{{ ip }}/restapi/v2/physicalmachines/systemshutdown"
        headers:
          Authorization: "Bearer {{ access }}" 
          Content-Type: 'application/json'
        body_format: json
        body: '{
        }'
        validate_certs: no
        follow_redirects: all
        return_content: yes
        status_code: 200
        method: POST
      register: result

    - name: STATUS
      ansible.builtin.debug:
        var: result.content
