---

- name: List VM API
  hosts: localhost
  vars_prompt:
    - name: ip
      prompt: Enter System IP
      private: false
  vars:
    access: "{{ lookup('file','token_{{ ip }}.yaml') }}"
  tasks:
    - name: Fetching VM Information
      uri:
        url: "https://{{ ip }}/restapi/v2/resource/virtualmachines"
        headers:
          Authorization: "Bearer {{ access }}" 
          Content-Type: 'application/json'
        validate_certs: no
        follow_redirects: all
        return_content: yes
        status_code: 200
        method: GET
      register: result

    - name: STATUS
      ansible.builtin.debug:
        var: result.content
