 - name: Virtual Machine Creation
   hosts: localhost
   vars_prompt:
    - name: address
      prompt: Enter System IP
      private: false
    - name: usrname
      prompt: Enter Username
      private: false
    - name: pswrd
      prompt: Enter Password
      private: true
    - name: vmname
      prompt: Enter VM Name
      private: false
    - name: description
      prompt: Enter Description
      private: false
    - name: bootType
      prompt: Enter Boot Type
      private: false
    - name: virtualCpus
      prompt: Enter Number of Virtual CPUs
      private: false
    - name: memory
      prompt: Enter Memory Size
      private: false
    - name: availabilityLevel
      prompt: Enter Availablity Level
      private: false
    - name: prefferednode
      prompt: Enter Preffered Node
      private: false
    - name: volumes
      prompt: Enter Number of Volumes
      private: false
    - name: remotetype
      prompt: Enter Remote Type
      private: false
    - name: remoteisopath
      prompt: Enter Remote ISO Path
      private: false
    - name: network
      prompt: Enter Network
      private: false
   vars:
     access: "{{ lookup('file','token_{{ address }}.yaml') }}"
     ip_file: "ipfile.yaml"
   tasks:
   - name: Login Authentication
     include_tasks: logintask.yaml
     vars:
       ip: "{{ address }}"
       token: "token_{{ address }}.yaml"
       refresh: "refreshToken_{{ address }}.yaml"
   - name: Creating VM "{{ address }}"
     ansible.builtin.uri:
        url: "https://{{ ip }}/restapi/v2/virtualmachines/vmcreate"
        headers:
          Authorization: "Bearer {{ access }}"
          Content-Type: 'application/json'
        method: POST
        body_format: json
        body: '{
          "vmname": "{{vmname}}",
          "description": "{{description}}",
          "bootType": "{{bootType}}",
          "virtualCpus": "{{virtualCpus}}",
          "memory": "{{memory}}",
          "availabilityLevel": "{{availabilityLevel}}",
          "prefferednode": "{{prefferednode}}",
          "volumes": ["{{volumes}}"],
          "remotetype": "{{remotetype}}",
          "remoteisopath": "{{remoteisopath}}",
          "network": ["{{network}}"]
        }'
        validate_certs: no
        status_code: 200
        timeout: 100
     register: result
   - name: Status
     ansible.builtin.debug:
        var: result


   - name: Logout
     include_tasks: logouttask.yaml
     vars:
        ip: "{{ address }}"
        token: "token_{{ ip }}.yaml"
        refresh: "refreshToken_{{ ip }}.yaml"
        access: "{{ lookup('file','token_{{ ip }}.yaml') }}"
        wtok: "null"
