---

- name: VM Power ON Workflow
  hosts: localhost
#  vars_prompt:
#    - name: address
#      prompt: Enter System IP
#      private: false
#  tasks:
#    - set_fact:
#        ip_global: 'address'

- name: Login Authentication
  import_playbook: login.yaml

- name: Summary
  import_playbook: summary.yaml

- name: VM info
  ansible.builtin.import_playbook: virtualmachines.yaml

- name: VM Shutdown
  ansible.builtin.import_playbook: vmpoweron.yaml

- name: VM info
  ansible.builtin.import_playbook: virtualmachines.yaml


- name: Logout
  ansible.builtin.import_playbook: logout.yaml
