    - name: Putting {node} on Mainatinance
      uri:
        url: "https://{{ ip }}/restapi/v2/physicalmachines/workon"
        headers:
          Authorization: "Bearer {{ access }}" 
          Content-Type: 'application/json'
        body_format: json
        body: '{
          "nodeName": "{{node}}",
          "force": "{{frce}}"
        }'
        validate_certs: no
        follow_redirects: all
        return_content: yes
        status_code: 200
        method: POST
      register: result

    - name: STATUS
      ansible.builtin.debug:
        var: result.content
